### ISSUE TITLE
looking for the paper about this

### ISSUE THREAD

**Issue by 734411268** [jogecodes/transformerAD#1]
I am looking for this paper to read. May I ask where I can find it? I have been searching for it for a long time but haven't found it yet

**Comment by jogecodes** [comment]
Hello fella! It is yet to be published, but you'll be able to check it out by the end of July :-)

**Comment by 734411268** [comment]
Okay, thank you for your prompt reply. I feel it will be of great help to me. I am looking forward to seeing your paper soon.

**Comment by jogecodes** [comment]
Thank you for your interest actually, as a novel scientist it felt nice to raise some. I'll make sure to forward you a link as soon as it is published. Regards!

**Comment by 734411268** [comment]
I will leave my email and hope to communicate with you more in the future mail：734411268@qq.com

**Comment by jogecodes** [comment]
Hello again! The paper is already out (I just received the notification). You can check it out at https://ieeexplore.ieee.org/abstract/document/10224965 or ask me, if you need it, for a manuscript copy at jorge.casajus@alumnos.upm.es.

Cheers, hope you enjoy it!
